### ISSUE TITLE
OCW hook

### ISSUE THREAD

**Issue by pdpinch** [mitodl/course-catalog#16]
a celery task for checking the OCW JSON export bucket for new course data

**Comment by pdpinch** [comment]
Given the relative infrequency of OCW updates, and the resources required for doing an update, we're rethinking the approach of scheduling updates daily.

**Comment by kyfantaz** [comment]
That's fine. We don't need to schedule it as a regular cron task. We should still have a single function call as available as a hook, if you ever do need a sync in the future
.

**Comment by pdpinch** [comment]
What we would like is an HTTP endpoint that can will kick off an update when it received a GET request. 

And then we'll set up an AWS notification based off of changes to the S3 bucket.
