### ISSUE TITLE
export edX discovery API response to S3

### ISSUE THREAD

**Issue by pdpinch** [mitodl/course-catalog#51]
We would like to expose the results of the edX discovery API to the OCW web site as well, in order to support the functionality of the page currently at https://ocw.mit.edu/courses/mitx-related-courseware/

The easiest path would appear to be to export the json data collected in `get_edx_data` and save it to open learning course data S3 bucket. 

A separate OCW task will take care of moving the file to OCW's CDN.

**Comment by pdpinch** [comment]
Question: is it reasonable to serialize the API response to one file, without pagination? That will make it easier for the JavaScript that consume it.

**Comment by sesterki** [comment]
We store the edX data in a flat format like below. Should the JSON we upload just be this format or do we need another format?:
```
{
    'course_id': 'course-v1:MITx+17.TAEx+1T2019',
    'title': 'Tools for Academic Engagement in Public Policy',
    'short_description': None,
    'level': None,
    'semester':
    'spring',
    'language': None,
    'platform':'mitx',
    'year': 2019,
    'full_description': None,
    'start_date': None,
    'end_date': datetime.datetime(2019, 6, 19, 23, 30, tzinfo= < UTC > ),
    'enrollment_start': None,
    'enrollment_end': None,
    'image_src': None,
    'image_description': None,
    'last_modified': datetime.datetime(2019, 1, 22, 12, 39, 53, 321681, tzinfo= < UTC > ),
    'raw_json': ""
}
```

**Comment by pdpinch** [comment]
I think we're losing too much of the original data here. Can we just de-paginate and dump that out?

**Comment by kyfantaz** [comment]
Certainly. We currently get paginated responses like this:

> {
>     "count": 1335,
>     "next": "https://xxx.edx.org/api/v1/catalogs/xxx/courses/?limit=20&offset=20"
>     "previous": # previous url 
>     "results": [...]  # one page of results, defaults to 20
> }

How about something like this?

> {
>     "count": 1335,
>     "catalog_url": "https://xxx.edx.org/api/v1/catalogs/xxx/courses/"
>     "results": [...] # all the results
> }
>

**Comment by pdpinch** [comment]
this was handled over in mitodl/open-discussions
